services:
  - type: web
    name: pdf-word-api
    env: java
    plan: free
    region: oregon
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -jar target/*.jar"
    envVars:
      - key: PORT
        value: 8080
