spring.application.name=pdf-word
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
server.port: 8080

jodconverter.local.enabled=true

#when running on local system 
#jodconverter.local.office-home=C:\Program Files\LibreOffice\program
#jodconverter.local.port-numbers=2002

#when running render.com server
jodconverter.local.office-home=/usr/lib/libreoffice
jodconverter.local.port-numbers=2002
