spring.application.name=pdf-word
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
server.port: 8080

jodconverter.local.enabled=true
jodconverter.local.office-home=C:\Program Files\LibreOffice\program
jodconverter.local.port-numbers=2002
